### ISSUE TITLE
Knex not recognized 

### ISSUE THREAD

**Issue by dwarak123** [TRUEPIC/queryql#7]
Hello, 

I am trying to setup a simple filter my code looks like this below:

const QueryQL = require('@truepic/queryql')

class UsedFlag extends QueryQL {
  defineSchema(dev_CareRecipients) {
    dev_CareRecipients.filter('UsedFlag', '=')
    dev_CareRecipients.page()
  }
}

router.get('/', async (req, res) => {
  const querier = new UsedFlag(req.query, knex('dev_CareRecipients'))
  let dev_CareRecipients

    try {
      dev_CareRecipients = await querier.run()
    } catch (error) {
      // Handle validation error, such as by passing to an Express error handler:
      next(error)
    }
  
    res.send({ dev_CareRecipients })
  })

My url looks like this below

GET http://vm213062fc:3000/dev_CareRecipients?filter[UsedFlag]=false&page=[size]=10
Could you please let me know if I am going wrong anywhere please

**Comment by jstayton** [comment]
Can you post the full error that you're getting?

The only thing that stands out to me is the query string `page=[size]=10` should be `page[size]=10`.

**Comment by dwarak123** [comment]
Hello Thanks for looking into this issue.....Please find below the detailed error message 

(node:8956) UnhandledPromiseRejectionWarning: ReferenceError: knex is not defined
    at C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\routes\dev\CareRecipients.js:18:40
    at Layer.handle [as handle_request] (C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\layer.js:95:5)
    at C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\index.js:335:12)
    at next (C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\index.js:275:10)
    at Function.handle (C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\index.js:174:3)
    at router (C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\index.js:47:12)
    at Layer.handle [as handle_request] (C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\layer.js:95:5)
    at trim_prefix (C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\index.js:317:13)
    at C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\index.js:284:7
    at Function.process_params (C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\index.js:335:12)
    at next (C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\express\lib\router\index.js:275:10)
    at jsonParser (C:\AUT\AUT\trunk\Aged Care API\Angular\RestHub\node_modules\body-parser\lib\types\json.js:110:7)
(node:8956) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:8956) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by jstayton** [comment]
Sorry if the documentation wasn't clear, but you do need to be using [Knex](https://knexjs.org/)  to query your database (or an ORM that uses Knex) for QueryQL to work. The `knex('dev_CareRecipients')` that you pass in to the QueryQL constructor needs to be a working Knex instance.

If you are, it doesn't look like you're requiring it correctly.

If you're not, you can write your own adapter, but that requires more work.

Let me know if you need more help.
